"""
Trade Models - Trade plans, execution receipts, positions.
"""
from datetime import datetime
from decimal import Decimal
from typing import Optional
from sqlalchemy import text, String, Integer, Boolean, Text, BigInteger, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, generate_uuid


class TradePlan(Base):
    """
    Trade plans generated by the Orchestrator.
    Contains the full decision rationale and parameters.
    """
    __tablename__ = "trade_plans"
    
    plan_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        unique=True,
        nullable=False,
        default=generate_uuid
    )
    correlation_id: Mapped[Optional[str]] = mapped_column(
        UUID(as_uuid=False),
        nullable=True,
        index=True
    )
    
    timestamp: Mapped[datetime] = mapped_column(nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    
    # Decision
    decision: Mapped[str] = mapped_column(String(20), nullable=False, index=True)  # BUY, SELL, WATCHLIST, NO_TRADE
    direction: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)  # long, short
    
    # Entry/Exit levels
    entry_type: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)  # market, limit, stop
    entry_price: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    stop_loss: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    take_profit_1: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    take_profit_2: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    
    # Risk
    risk_percent: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    lot_size: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    
    # Context
    strategy_family: Mapped[Optional[str]] = mapped_column(String(50), nullable=True, index=True)
    regime: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    timeframe: Mapped[Optional[str]] = mapped_column(String(5), nullable=True)
    
    # Scoring
    confluence_score: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    score_breakdown: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    
    # Evidence
    supporting_evidence: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    contradicting_evidence: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    hard_gates_result: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    vetoes_result: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    
    # Rationale (plain English)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    rationale_direction: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    rationale_location: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    rationale_timing: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    invalidation_thesis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    risk_sizing_rationale: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Execution
    execution_mode: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)  # paper, shadow, live
    
    # Snapshot of all agent inputs at decision time
    agent_snapshot: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    
    # Relationships
    execution_receipts: Mapped[list["ExecutionReceipt"]] = relationship(back_populates="trade_plan")
    positions: Mapped[list["Position"]] = relationship(back_populates="trade_plan")
    
    __table_args__ = (
        Index("ix_trade_plans_decision", "decision", text("timestamp DESC")),
    )


class ExecutionReceipt(Base):
    """
    Record of actual execution events.
    Links trade plans to what actually happened.
    """
    __tablename__ = "execution_receipts"
    
    receipt_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        unique=True,
        nullable=False,
        default=generate_uuid
    )
    plan_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("trade_plans.plan_id"),
        nullable=False
    )
    
    timestamp: Mapped[datetime] = mapped_column(nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    
    execution_mode: Mapped[str] = mapped_column(String(20), nullable=False)  # paper, shadow, live
    action: Mapped[str] = mapped_column(String(20), nullable=False)  # open, modify, close_partial, close_full
    direction: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)
    
    # Prices
    requested_price: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    fill_price: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    slippage_pips: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    spread_at_exec: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    
    lot_size: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    
    # Verification
    stop_confirmed: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    tp_confirmed: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    
    # Broker data
    broker_ticket: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    latency_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    # Quality
    health_score: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    warnings: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    errors: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    
    # Relationships
    trade_plan: Mapped["TradePlan"] = relationship(back_populates="execution_receipts")


class Position(Base, TimestampMixin):
    """
    Open and closed positions.
    Tracks the full lifecycle of a trade.
    """
    __tablename__ = "positions"
    
    position_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        unique=True,
        nullable=False,
        default=generate_uuid
    )
    plan_id: Mapped[Optional[str]] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("trade_plans.plan_id"),
        nullable=True
    )
    
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)  # long, short
    status: Mapped[str] = mapped_column(String(20), nullable=False, index=True)  # OPEN, CLOSED, PARTIAL
    
    # Entry
    entry_price: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    entry_time: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    
    # Current state
    current_stop: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    current_tp: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    lot_size: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    lot_size_remaining: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    risk_percent: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    
    # Exit
    exit_price: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    exit_time: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    exit_type: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)  # stop_loss, take_profit, manual, etc.
    
    # Results
    result_r: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    result_pips: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    result_currency: Mapped[Optional[Decimal]] = mapped_column(nullable=True)
    
    # Excursion tracking
    mae_pips: Mapped[Optional[Decimal]] = mapped_column(nullable=True)  # Maximum Adverse Excursion
    mfe_pips: Mapped[Optional[Decimal]] = mapped_column(nullable=True)  # Maximum Favorable Excursion
    
    # Execution mode
    execution_mode: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    broker_ticket: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)
    
    # Relationships
    trade_plan: Mapped[Optional["TradePlan"]] = relationship(back_populates="positions")
    
    __table_args__ = (
        Index("ix_positions_lookup", "symbol", text("entry_time DESC")),
    )
