"""
Strategy Selection Agent
========================
Evaluates all registered strategies against the current market context
and selects the most appropriate one (or none).

From 05_STRATEGY_ENGINE.txt:
Strategies are evaluated based on regime compatibility, confluence,
and setup quality.
"""
import structlog
from datetime import datetime, timezone
from typing import Any, Optional
from dataclasses import dataclass, field

from app.agents.base_agent import BaseAgent, AgentMessage, AgentHealthStatus

logger = structlog.get_logger()


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    strategy_name: str
    strategy_version: str = "1.0.0"
    symbol: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    direction: str = ""  # "long" or "short"
    entry_type: str = "market"  # "market", "limit", "stop"
    entry_price: Optional[float] = None
    stop_loss: float = 0.0  # MANDATORY
    take_profit_1: Optional[float] = None
    take_profit_2: Optional[float] = None
    
    risk_reward_ratio: float = 0.0
    setup_quality: float = 0.0  # 0.0 to 1.0
    confidence: float = 0.0  # 0.0 to 1.0
    
    rationale: str = ""
    invalidation: str = ""
    supporting_factors: list = field(default_factory=list)
    contradicting_factors: list = field(default_factory=list)
    
    # Filters
    required_regime: list = field(default_factory=list)
    max_spread_pips: float = 3.0
    min_atr_pips: float = 5.0
    valid_until: Optional[datetime] = None


@dataclass
class StrategyEvaluation:
    """Evaluation result for a single strategy."""
    strategy_name: str
    was_eligible: bool = False
    ineligibility_reason: Optional[str] = None
    signal_generated: bool = False
    signal_quality: Optional[float] = None
    signal_confidence: Optional[float] = None
    signal: Optional[StrategySignal] = None


@dataclass
class StrategySelectionResult:
    """Result of strategy selection process."""
    symbol: str
    timestamp: datetime
    
    selected_strategy: Optional[str] = None
    selected_signal: Optional[StrategySignal] = None
    selection_score: float = 0.0
    
    all_evaluated: list = field(default_factory=list)
    reasons_for_selection: list = field(default_factory=list)
    reasons_others_rejected: dict = field(default_factory=dict)


# Strategy definitions with their allowed/invalid regimes
STRATEGY_CONFIGS = {
    "trend_continuation": {
        "allowed_regimes": ["trending_strong", "trending_weak"],
        "invalid_regimes": ["range_bound", "unstable_noisy", "mean_reverting"],
        "required_adx": 20,
        "description": "Enter in trend direction after pullback to key level",
    },
    "pullback_in_trend": {
        "allowed_regimes": ["trending_strong", "trending_weak"],
        "invalid_regimes": ["range_bound", "unstable_noisy"],
        "required_adx": 18,
        "description": "Target pullbacks to EMA zones in established trends",
    },
    "breakout": {
        "allowed_regimes": ["breakout_ready", "range_bound"],
        "invalid_regimes": ["unstable_noisy", "low_volatility_drift"],
        "description": "Trade breakout of consolidation boundaries",
    },
    "range_fade": {
        "allowed_regimes": ["range_bound", "mean_reverting"],
        "invalid_regimes": ["trending_strong", "breakout_ready", "high_volatility_expansion"],
        "max_adx": 20,
        "description": "Fade range boundaries in mean-reverting conditions",
    },
    "failed_breakout_reversal": {
        "allowed_regimes": ["range_bound", "mean_reverting", "trending_weak"],
        "invalid_regimes": ["trending_strong"],
        "description": "Trade reversal after failed breakout traps traders",
    },
    "volatility_expansion": {
        "allowed_regimes": ["breakout_ready", "low_volatility_drift"],
        "invalid_regimes": ["high_volatility_expansion"],
        "description": "Capture expansion moves after compression",
    },
}


class StrategySelectionAgent(BaseAgent):
    """
    Strategy Selection Agent.
    
    Evaluates strategies against current market conditions and selects
    the best one (or none if no setup qualifies).
    """
    
    def __init__(
        self,
        name: str = "strategy_selection_agent",
        config: Optional[dict[str, Any]] = None,
    ):
        super().__init__(name, config)
        
        self.strategies = STRATEGY_CONFIGS
        self.min_setup_quality = config.get("min_setup_quality", 0.5) if config else 0.5
        self.min_confidence = config.get("min_confidence", 0.5) if config else 0.5
    
    async def initialize(self) -> None:
        """Initialize the agent."""
        self.is_initialized = True
        self.is_running = True
        self.started_at = datetime.now(timezone.utc)
        self._logger.info(
            "Strategy Selection Agent initialized",
            strategies=list(self.strategies.keys()),
        )
    
    async def run(self, context: dict[str, Any]) -> AgentMessage:
        """
        Select the best strategy for current conditions.
        
        Args:
            context: Must contain:
                - symbol: Trading symbol
                - technical: TechnicalAssessment
                - structure: MarketStructureAssessment
                - regime: RegimeAssessment
                - market_data: Market data snapshot
        """
        symbol = context.get("symbol")
        technical = context.get("technical")
        structure = context.get("structure")
        regime = context.get("regime")
        
        if not all([symbol, technical, regime]):
            return self._create_message(
                message_type="error",
                payload={"error": "Missing required context"},
                symbol=symbol,
                confidence=0.0,
                errors=["Missing symbol, technical, or regime data"],
            )
        
        # Perform selection
        result = await self._select_strategy(symbol, technical, structure, regime, context)
        
        return self._create_message(
            message_type="strategy_selection",
            payload=self._result_to_dict(result),
            symbol=symbol,
            confidence=result.selection_score if result.selected_signal else 0.0,
        )
    
    async def _select_strategy(
        self,
        symbol: str,
        technical: dict,
        structure: Optional[dict],
        regime: dict,
        context: dict,
    ) -> StrategySelectionResult:
        """Select the best strategy."""
        result = StrategySelectionResult(
            symbol=symbol,
            timestamp=datetime.now(timezone.utc),
        )
        
        current_regime = regime.get("current_regime", "unknown")
        recommended_strategies = regime.get("recommended_strategy_families", [])
        
        # Evaluate each strategy
        evaluations = []
        
        for strategy_name, strategy_config in self.strategies.items():
            eval_result = self._evaluate_strategy(
                strategy_name=strategy_name,
                strategy_config=strategy_config,
                symbol=symbol,
                technical=technical,
                structure=structure,
                current_regime=current_regime,
                recommended_strategies=recommended_strategies,
                context=context,
            )
            evaluations.append(eval_result)
            result.all_evaluated.append({
                "strategy_name": eval_result.strategy_name,
                "was_eligible": eval_result.was_eligible,
                "ineligibility_reason": eval_result.ineligibility_reason,
                "signal_generated": eval_result.signal_generated,
                "signal_quality": eval_result.signal_quality,
                "signal_confidence": eval_result.signal_confidence,
            })
        
        # Filter to eligible strategies with signals
        valid_signals = [
            e for e in evaluations
            if e.was_eligible and e.signal_generated and e.signal
        ]
        
        if not valid_signals:
            result.reasons_for_selection = ["No strategy found valid setup"]
            for e in evaluations:
                if e.ineligibility_reason:
                    result.reasons_others_rejected[e.strategy_name] = e.ineligibility_reason
            return result
        
        # Rank by quality * confidence
        ranked = sorted(
            valid_signals,
            key=lambda e: (e.signal_quality or 0) * (e.signal_confidence or 0),
            reverse=True,
        )
        
        # Select best
        best = ranked[0]
        result.selected_strategy = best.strategy_name
        result.selected_signal = best.signal
        result.selection_score = (best.signal_quality or 0) * (best.signal_confidence or 0)
        
        # Document selection reasons
        result.reasons_for_selection = [
            f"Best quality/confidence: {result.selection_score:.2f}",
            f"Regime compatible: {current_regime}",
        ]
        if best.signal:
            result.reasons_for_selection.extend(best.signal.supporting_factors[:3])
        
        # Document rejection reasons for others
        for e in evaluations:
            if e.strategy_name != best.strategy_name:
                if e.ineligibility_reason:
                    result.reasons_others_rejected[e.strategy_name] = e.ineligibility_reason
                elif e.signal_quality and e.signal_quality < (best.signal_quality or 0):
                    result.reasons_others_rejected[e.strategy_name] = f"Lower quality: {e.signal_quality:.2f}"
        
        return result
    
    def _evaluate_strategy(
        self,
        strategy_name: str,
        strategy_config: dict,
        symbol: str,
        technical: dict,
        structure: Optional[dict],
        current_regime: str,
        recommended_strategies: list,
        context: dict,
    ) -> StrategyEvaluation:
        """Evaluate a single strategy."""
        eval_result = StrategyEvaluation(strategy_name=strategy_name)
        
        # CHECK 1: Regime compatibility
        allowed = strategy_config.get("allowed_regimes", [])
        invalid = strategy_config.get("invalid_regimes", [])
        
        if current_regime in invalid:
            eval_result.was_eligible = False
            eval_result.ineligibility_reason = f"Regime {current_regime} is invalid for this strategy"
            return eval_result
        
        if allowed and current_regime not in allowed:
            eval_result.was_eligible = False
            eval_result.ineligibility_reason = f"Regime {current_regime} not in allowed list"
            return eval_result
        
        # CHECK 2: Strategy in recommended list
        if strategy_name not in recommended_strategies:
            eval_result.was_eligible = False
            eval_result.ineligibility_reason = f"Not recommended for current regime"
            return eval_result
        
        eval_result.was_eligible = True
        
        # Try to generate signal
        signal = self._generate_signal(
            strategy_name=strategy_name,
            strategy_config=strategy_config,
            symbol=symbol,
            technical=technical,
            structure=structure,
            context=context,
        )
        
        if signal:
            eval_result.signal_generated = True
            eval_result.signal = signal
            eval_result.signal_quality = signal.setup_quality
            eval_result.signal_confidence = signal.confidence
        else:
            eval_result.signal_generated = False
            eval_result.ineligibility_reason = "No valid setup found"
        
        return eval_result
    
    def _generate_signal(
        self,
        strategy_name: str,
        strategy_config: dict,
        symbol: str,
        technical: dict,
        structure: Optional[dict],
        context: dict,
    ) -> Optional[StrategySignal]:
        """Generate a signal if setup conditions are met."""
        
        # Get technical data
        directional_lean = technical.get("directional_lean", "neutral")
        directional_strength = technical.get("directional_strength", 0)
        setup_type = technical.get("setup_type")
        setup_quality = technical.get("setup_quality", 0)
        mtf_alignment = technical.get("mtf_alignment", "mixed")
        
        # Get structure data
        structure_state = structure.get("structure_state", "unknown") if structure else "unknown"
        bullish_invalidation = structure.get("bullish_invalidation") if structure else None
        bearish_invalidation = structure.get("bearish_invalidation") if structure else None
        nearest_support = structure.get("nearest_support") if structure else None
        nearest_resistance = structure.get("nearest_resistance") if structure else None
        
        # Get current price
        market_data = context.get("market_data", {})
        current_price = market_data.get("current_price", 0)
        if not current_price:
            indicators = technical.get("indicators", {}).get("M30", {})
            current_price = indicators.get("current_price", 0)
        
        if not current_price:
            return None
        
        # Strategy-specific signal generation
        if strategy_name == "trend_continuation":
            return self._generate_trend_continuation_signal(
                symbol, current_price, directional_lean, directional_strength,
                setup_type, setup_quality, mtf_alignment, structure,
                bullish_invalidation, bearish_invalidation,
                nearest_support, nearest_resistance,
            )
        
        elif strategy_name == "pullback_in_trend":
            return self._generate_pullback_signal(
                symbol, current_price, directional_lean, directional_strength,
                setup_type, setup_quality, technical, structure,
            )
        
        elif strategy_name == "breakout":
            return self._generate_breakout_signal(
                symbol, current_price, technical, structure,
            )
        
        elif strategy_name == "range_fade":
            return self._generate_range_fade_signal(
                symbol, current_price, technical, structure,
            )
        
        # Default: no signal
        return None
    
    def _generate_trend_continuation_signal(
        self,
        symbol: str,
        price: float,
        direction: str,
        strength: float,
        setup_type: Optional[str],
        setup_quality: float,
        mtf_alignment: str,
        structure: Optional[dict],
        bullish_inv: Optional[float],
        bearish_inv: Optional[float],
        support: Optional[dict],
        resistance: Optional[dict],
    ) -> Optional[StrategySignal]:
        """Generate trend continuation signal."""
        
        # Need clear direction and pullback setup
        if direction == "neutral" or strength < 0.4:
            return None
        
        if setup_type not in ["pullback", "compression"]:
            return None
        
        if setup_quality < self.min_setup_quality:
            return None
        
        # Need MTF alignment
        expected_alignment = f"aligned_{direction}"
        if mtf_alignment != expected_alignment and mtf_alignment != "mixed":
            return None
        
        # Build signal
        if direction == "bullish":
            stop_loss = bullish_inv if bullish_inv else price * 0.99
            tp1 = resistance["midpoint"] if resistance else price * 1.015
            entry_type = "limit" if support else "market"
            entry_price = support["midpoint"] if support else None
        else:
            stop_loss = bearish_inv if bearish_inv else price * 1.01
            tp1 = support["midpoint"] if support else price * 0.985
            entry_type = "limit" if resistance else "market"
            entry_price = resistance["midpoint"] if resistance else None
        
        # Calculate R:R
        stop_distance = abs(price - stop_loss)
        tp_distance = abs(tp1 - price) if tp1 else stop_distance * 1.5
        rr_ratio = tp_distance / stop_distance if stop_distance > 0 else 0
        
        if rr_ratio < 1.5:
            return None
        
        return StrategySignal(
            strategy_name="trend_continuation",
            symbol=symbol,
            direction="long" if direction == "bullish" else "short",
            entry_type=entry_type,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit_1=tp1,
            risk_reward_ratio=rr_ratio,
            setup_quality=setup_quality,
            confidence=strength * 0.8 + (0.2 if mtf_alignment == expected_alignment else 0),
            rationale=f"Trend continuation in {direction} trend after pullback",
            invalidation=f"Break below {'support' if direction == 'bullish' else 'resistance'}",
            supporting_factors=[
                f"Direction: {direction} ({strength:.0%})",
                f"MTF: {mtf_alignment}",
                f"Setup: {setup_type} ({setup_quality:.0%})",
            ],
            required_regime=["trending_strong", "trending_weak"],
        )
    
    def _generate_pullback_signal(
        self,
        symbol: str,
        price: float,
        direction: str,
        strength: float,
        setup_type: Optional[str],
        setup_quality: float,
        technical: dict,
        structure: Optional[dict],
    ) -> Optional[StrategySignal]:
        """Generate pullback in trend signal."""
        
        if direction == "neutral" or strength < 0.3:
            return None
        
        # Check if at EMA zone
        indicators = technical.get("indicators", {}).get("M30", {})
        ema_cluster = indicators.get("ema_cluster", {})
        rsi = indicators.get("rsi", {})
        
        ema_21 = ema_cluster.get("ema_21", 0)
        ema_50 = ema_cluster.get("ema_50", 0)
        
        if not ema_21 or not ema_50:
            return None
        
        # Price should be near EMA zone
        ema_zone_mid = (ema_21 + ema_50) / 2
        distance_pct = abs(price - ema_zone_mid) / price * 100
        
        if distance_pct > 0.5:  # Not at EMA zone
            return None
        
        # RSI should not be extreme
        rsi_value = rsi.get("value", 50)
        if direction == "bullish" and rsi_value > 65:
            return None
        if direction == "bearish" and rsi_value < 35:
            return None
        
        # Build signal
        atr = indicators.get("volatility", {}).get("atr", 0.001)
        
        if direction == "bullish":
            stop_loss = min(ema_50, price) - atr * 1.5
            tp1 = price + atr * 2
        else:
            stop_loss = max(ema_50, price) + atr * 1.5
            tp1 = price - atr * 2
        
        stop_distance = abs(price - stop_loss)
        rr_ratio = abs(tp1 - price) / stop_distance if stop_distance > 0 else 0
        
        return StrategySignal(
            strategy_name="pullback_in_trend",
            symbol=symbol,
            direction="long" if direction == "bullish" else "short",
            entry_type="limit",
            entry_price=ema_zone_mid,
            stop_loss=stop_loss,
            take_profit_1=tp1,
            risk_reward_ratio=rr_ratio,
            setup_quality=0.6,
            confidence=strength * 0.7,
            rationale=f"Pullback to EMA zone in {direction} trend",
            invalidation="Break of EMA zone",
            supporting_factors=[
                f"At EMA zone ({distance_pct:.1f}% away)",
                f"RSI neutral: {rsi_value:.0f}",
            ],
            required_regime=["trending_strong", "trending_weak"],
        )
    
    def _generate_breakout_signal(
        self,
        symbol: str,
        price: float,
        technical: dict,
        structure: Optional[dict],
    ) -> Optional[StrategySignal]:
        """Generate breakout signal."""
        
        if not technical.get("is_compressed"):
            return None
        
        breakout_potential = technical.get("breakout_potential", 0)
        if breakout_potential < 0.5:
            return None
        
        # Need clear levels from structure
        if not structure:
            return None
        
        support = structure.get("nearest_support")
        resistance = structure.get("nearest_resistance")
        
        if not support or not resistance:
            return None
        
        support_price = support.get("midpoint", 0)
        resistance_price = resistance.get("midpoint", 0)
        
        range_size = resistance_price - support_price
        if range_size <= 0:
            return None
        
        # Bias from higher timeframe
        mtf = technical.get("mtf_alignment", "mixed")
        
        if mtf == "aligned_bullish":
            direction = "long"
            entry_price = resistance_price + range_size * 0.1  # Stop entry above resistance
            stop_loss = support_price
            tp1 = entry_price + range_size  # Measured move
        elif mtf == "aligned_bearish":
            direction = "short"
            entry_price = support_price - range_size * 0.1
            stop_loss = resistance_price
            tp1 = entry_price - range_size
        else:
            return None  # No clear bias
        
        rr_ratio = abs(tp1 - entry_price) / abs(entry_price - stop_loss)
        
        return StrategySignal(
            strategy_name="breakout",
            symbol=symbol,
            direction=direction,
            entry_type="stop",
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit_1=tp1,
            risk_reward_ratio=rr_ratio,
            setup_quality=breakout_potential,
            confidence=0.6,
            rationale=f"Breakout from compression with {mtf} bias",
            invalidation="Failed breakout / price reclaims range",
            supporting_factors=[
                f"Compressed volatility",
                f"HTF bias: {mtf}",
                f"Range: {range_size:.5f}",
            ],
            required_regime=["breakout_ready"],
        )
    
    def _generate_range_fade_signal(
        self,
        symbol: str,
        price: float,
        technical: dict,
        structure: Optional[dict],
    ) -> Optional[StrategySignal]:
        """Generate range fade signal."""
        
        if not structure:
            return None
        
        price_location = structure.get("price_location", "")
        
        if price_location not in ["at_support", "at_resistance"]:
            return None
        
        # Check for reversal confirmation
        rsi = technical.get("indicators", {}).get("M30", {}).get("rsi", {})
        
        if price_location == "at_support":
            if not rsi.get("is_oversold"):
                return None
            direction = "long"
            support = structure.get("nearest_support", {})
            resistance = structure.get("nearest_resistance", {})
            if not support or not resistance:
                return None
            stop_loss = support.get("lower_bound", price * 0.99)
            tp1 = (support.get("midpoint", price) + resistance.get("midpoint", price)) / 2
            
        else:  # at_resistance
            if not rsi.get("is_overbought"):
                return None
            direction = "short"
            support = structure.get("nearest_support", {})
            resistance = structure.get("nearest_resistance", {})
            if not support or not resistance:
                return None
            stop_loss = resistance.get("upper_bound", price * 1.01)
            tp1 = (support.get("midpoint", price) + resistance.get("midpoint", price)) / 2
        
        stop_distance = abs(price - stop_loss)
        rr_ratio = abs(tp1 - price) / stop_distance if stop_distance > 0 else 0
        
        if rr_ratio < 1.0:
            return None
        
        return StrategySignal(
            strategy_name="range_fade",
            symbol=symbol,
            direction=direction,
            entry_type="market",
            entry_price=price,
            stop_loss=stop_loss,
            take_profit_1=tp1,
            risk_reward_ratio=rr_ratio,
            setup_quality=0.5,
            confidence=0.5,
            rationale=f"Range fade at {price_location.replace('at_', '')}",
            invalidation="Break of range boundary",
            supporting_factors=[
                f"At {price_location}",
                f"RSI extreme: {rsi.get('value', 50):.0f}",
            ],
            required_regime=["range_bound", "mean_reverting"],
        )
    
    def _result_to_dict(self, result: StrategySelectionResult) -> dict:
        """Convert result to serializable dict."""
        signal_dict = None
        if result.selected_signal:
            s = result.selected_signal
            signal_dict = {
                "strategy_name": s.strategy_name,
                "direction": s.direction,
                "entry_type": s.entry_type,
                "entry_price": s.entry_price,
                "stop_loss": s.stop_loss,
                "take_profit_1": s.take_profit_1,
                "risk_reward_ratio": s.risk_reward_ratio,
                "setup_quality": s.setup_quality,
                "confidence": s.confidence,
                "rationale": s.rationale,
                "invalidation": s.invalidation,
                "supporting_factors": s.supporting_factors,
            }
        
        return {
            "symbol": result.symbol,
            "timestamp": result.timestamp.isoformat(),
            "selected_strategy": result.selected_strategy,
            "selected_signal": signal_dict,
            "selection_score": result.selection_score,
            "all_evaluated": result.all_evaluated,
            "reasons_for_selection": result.reasons_for_selection,
            "reasons_others_rejected": result.reasons_others_rejected,
        }
    
    async def health_check(self) -> AgentHealthStatus:
        return AgentHealthStatus(
            agent_name=self.name,
            is_healthy=self.is_initialized,
            last_run=self.last_run,
            last_success=self.last_success,
            last_error=self.last_error,
            consecutive_failures=self.consecutive_failures,
            uptime_seconds=self._get_uptime_seconds(),
        )
    
    def get_dependencies(self) -> list[str]:
        return [
            "market_data_agent",
            "technical_analysis_agent",
            "market_structure_agent",
            "regime_detection_agent",
        ]
